
version: 2

# jobs refer to a single execution of the build
jobs:
  # build is the name of the job....they can be multiple and unique
  build:
    # builds occur in a docker container
    docker:
      - image: circleci/python:3.7
      # - image: njogu487/ubuntu1804:latest
    # environment:
    #   - ANSIBLE_HOST_KEY_CHECKING: False
    working_directory: ~/repo

    # series/ list of steps done for the build
    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv last
            . last/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            sudo apt install rsync
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . last/bin/activate
            
            coverage run --source="." manage.py test
            coverage report --fail-under=100
           



  deploy:
    docker:
      - image: circleci/python:3.7
    environment:
      - ANSIBLE_HOST_KEY_CHECKING: False
    steps:
      - checkout
      # - run:
      #     name: verify git tag vs. version
      #     command: |
      #       python3 -m venv last
      #       . last/bin/activate
      #       python setup.py verify

      - run:
          name: pypi initialization
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = cuttice" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc      

      - run:
          name: create packages
          command: |
            python3 setup.py sdist bdist_wheel
           

      - run:
          name: upload to pypi
          command: |
            python3 -m venv last
            . last/bin/activate
            pip install twine
            twine upload dist/*
      
      - add_ssh_keys:
          fingerprints:
              - "87:3d:6f:60:9e:60:fb:e4:a7:85:95:99:a5:a4:d8:4a"
      # # - run:
      #     # name: Make remote server a known host
      #     # command: ssh-keyscan josephdevs.duckdns.org >> ~/.ssh/known_hosts 
      - run:
          name: executing ansible to a aws
          command: |
            python3 -m venv last
            . last/bin/activate
            pip install ansible
            cd ansible
            ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i hosts provision.yml
           


workflows:
  version: 2
  build_deploy:
    jobs:
    - build
    - deploy:
        requires:
          - build
        filters:
          branches:
            only: master