version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6
    environment: 
        ANSIBLE_HOST_KEY_CHECKING: False
    steps:
      - checkout
      
      - run:
          name: install python dependencies
          command: |
           pip install --user --upgrade pip
           python3 -m venv last
           . last/bin/activate
           pip3 install -r requirements.txt
           pip3 install ansible
           sudo apt update
           sudo apt install rsync
    
      - run:
          name: run tests
          command: |
           . last/bin/activate
           tox
           coverage run --source='.' manage.py test
           coverage report --fail-under=76
      - store_artifacts:
          path: htmlcov/
 
      
      - run:
          name: install python dependencies
          command: |
            pip install --upgrade pip
            python3 -m venv las
            . last/bin/activate
            pip3 install -r requirements.txt
      
      - run:
          name: run tests
          command: |
           . last/bin/activate
           coverage run --source='.' manage.py test
           coverage report -m
     
workflows:
  build:
    jobs:
      - publish:
          filters:
            
            branches:
              only: master
      
  
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = cuttice" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: create packages
          command: |
            python setup.py sdist bdist_wheel
      - run:
          name: upload to pypi
          command: |
            . last/bin/activate
            twine upload dist/*

      - run:
          name: Deploy 
          command: |
              . last/bin/activate
              ansible-playbook -i ansible/hosts ansible/provision.yml

  