---
- hosts: web
  vars_files:
    - vars.yml
  gather_facts: false
  become: yes

  tasks:
    - name: Install pip
      apt:
        name: python3-pip
        update_cache: yes
        state: latest

    - name: Upgrade pip
      pip: name=pip state=latest

    - name: Create directory for app
      file: path={{ install_root }}/{{ project_name }} state=directory

    - name: Recursively change ownership of a directory
      file:
        path: /home/johnson/app/AppRepo
        state: directory
        recurse: yes
        owner: johnson

    - name: Pull project from github
      git:
        repo: 'https://github.com/Jonnybuoy/AppRepo.git'
        dest: app/AppRepo/
        update: no


    - name: Install project requirements
      pip:
        requirements: /home/johnson/app/AppRepo/requirements.txt


    - name: copy nginx config
      copy:
        src: /home/johnson/app/AppRepo/ansible/files/nginx.j2
        dest: /etc/nginx/sites-available/AppRepo
        remote_src: yes


    - name: Create symbolic link
      file:
        src: /etc/nginx/sites-available/AppRepo
        dest: /etc/nginx/sites-enabled/AppRepo
        state: link


    - name: make sure nginx server is running
      service:
        name: nginx
        state: started
        enabled: yes

    - name: make sure postgresql server is running
      service: name=postgresql state=started

    - name: create database
      become_user: postgres
      postgresql_db: name=circle_test

    - name: Configure a new postgresql user
      become: true
      become_user: postgres
      postgresql_user: db=circle_test
                                  name=postgres
                                  password=password
                                  encrypted=yes
                                  priv=ALL
                                  role_attr_flags=NOSUPERUSER
      become: yes
      become_user: postgres


    - name: Make migrations
      shell:
        python3 /home/johnson/app/AppRepo/manage.py migrate


    - name: start gunicorn
      become: True
      command: gunicorn --daemon --workers 3 --bind unix:/home/johnson/app/AppRepo/AppRepo.sock listproject.wsgi
      args:
        chdir: /home/johnson/app/AppRepo



    - name: Enable UFW
      ufw:
        state: enabled

    - name: Allow OpenSSH
      ufw:
        rule: allow
        name: OpenSSH

    - name: Allow Nginx full
      ufw:
        rule: allow
        name: Nginx Full

    - name: Obtain SSL certificate
      shell: "certbot --nginx --noninteractive --agree-tos --email kaguithiajohnson@gmail.com -d remindershoplist.duckdns.org -d www.remindershoplist.duckdns.org"
      become: yes



  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
