---
- hosts: webserver
  vars_files:
    - vars.yml
  gather_facts: false
  become: yes

  tasks:
    - name: Install system packages
      apt: pkg={{ item }} update-cache=yes
      with_items: "{{ system_packages }}"
      


    - name: add public key for certbot repo
      shell: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8C47BE8E75BCA694
      become: yes

    - name: add universe repository for bionic
      apt_repository:
        repo: ppa:certbot/certbot
        state: present

    - name: remove default nginx site
      file: path=/etc/nginx/sites-enabled/default state=absent


- include: playbook(1).yml
